name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/backend/requirements.txt
    # 新增步骤：在运行测试前创建 secure.json 文件
    - name: Create secure.json
      run: |
        # 确保目录存在
        mkdir -p ./src/backend/item_manager/
        # 使用 echo 和重定向操作符 > 来创建文件并写入内容
        echo '{
          "SECRET_KEY": "114514",
          "SMTP": {
            "EMAIL_HOST": "",
            "EMAIL_PORT": 465,
            "EMAIL_HOST_USER": "",
            "EMAIL_HOST_PASSWORD": "",
            "EMAIL_USE_SSL": true,
            "DEFAULT_FROM_EMAIL": "",
            "ADMINS": [["", ""]]
          }
        }' > ./src/backend/item_manager/secure.json
    - name: Run Tests
      run: |
        python ./src/backend/manage.py test
